apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: causely
  namespace: argocd
spec:
  project: causely
  destination:
    namespace: causely
    server: https://kubernetes.default.svc
  source:
    repoURL: us-docker.pkg.dev/public-causely/public
    chart: causely
    targetRevision: "v1.0.134-0-gd03a73b6ace6469f"
    helm:
      releaseName: causely
      parameters:
        - name: image.tag
          value: latest
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: mediator
      jqPathExpressions:
        - .spec.template.spec.containers[].image
    - group: apps
      kind: DaemonSet
      jqPathExpressions:
        - .spec.template.spec.containers[].image
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
