apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- release.yaml
- repository.yaml

postBuild:
  substitute:
    CAUSELY_VERSION: "v1.0.108-0-g5510e86517f165a5"
  substituteFrom:
    - kind: Secret
      name: causely-secrets