apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- release.yaml
- repository.yaml

postBuild:
  substitute:
    CAUSELY_VERSION: "v1.0.134-0-gd03a73b6ace6469f"