apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- release.yaml
- repository.yaml

postBuild:
  substitute:
    CAUSELY_VERSION: "v1.0.133-0-gf9fc2d89e2d4e8b3"